- .sqlfluff
- .sqlfluffignore
- .vscode/extensions.json
- .vscode/settings.json
- doc/installation.md
- macros/correct_schema.sql
- macros/get_fields.sql
- macros/test_not_null_syk.sql
- macros/test_unique_values_syk.sql
- models/dvh_syfo/dvh_syfo_all_models.yml
- models/dvh_syfo/forkammer/dim/stg_dim_naering.sql
- models/dvh_syfo/forkammer/dim/stg_dim_organisasjon.sql
- models/dvh_syfo/forkammer/dim/stg_dim_person1.sql
- models/dvh_syfo/forkammer/dim/stg_dim_tid.sql
- models/dvh_syfo/forkammer/dim/stg_dim_varighet.sql
- models/dvh_syfo/forkammer/modia/stg_fk_isdialogmote_dm2.sql
- models/dvh_syfo/kjerne/fak_syfo_dialogmote.sql
- models/dvh_syfo/kjerne/fak_syfo_dialogmote_org.sql
- models/dvh_syfo/kjerne/fak_syfo_dialogmote_tid.sql
- models/dvh_syfo/kjerne/fak_syfo_oppfolging_pvt.sql
- models/dvh_syfo/torg/fak_syfo_dt_dialogmote.sql
- tests/test_not_null_syk2.sql
- Remove unused tests and macros
- Add sqlfluff configuration
- Refactor style in stg_dim_naering
- Refacotr style in stg_dim_organisasjon
- Refactor style in stg_dim_person1
- Refactor style in stg_dim_tid
- Refactor style in stg_dim_varighet
- Refactor style in stg_fk_isdialogmote_dm2
- Refactor style in fak_syfo_dialogmote
- Refactor style in fak_syfo_dialogmote_org
- Refactor style in fak_syfo_dialogmote_tid
- Refactor style in fak_syfo_oppfolging_pvt
- Refactor style in fak_syfo_dt_dialogmote
- Switch recommended formatter extension to sqlfluff
- Update installation doc with sqlfluff
> SQLFluff configuration

- .gitignore
- models/dvh_syfo/schema.yml
- setup_db_user.ps1
Vi får falske warnings i helger på fershetstestene til SYFO dialogmøter.
> Justere ferskhetstester

- models/dvh_syfo/forkammer/modia/tmp__manglende_data_i_dm2.sql
- models/dvh_syfo/forkammer/modia/tmp__stg_isdialogmote.sql
- setup_db_user.ps1
Midlertidlig tabell med de datene radene fra modia for å patche dvh_syfo.fk_isdialogmote_dm2.
Jira: https://jira.adeo.no/browse/STO-2524
> Fiks tap av modiadata

- .sqlfluff
- macros/lest_fk_sporbar_utbetaling.sql
- models/sykp/_sykp__sources.yml
- models/sykp/fk_sporbar_utbetaling_kafka_offset.sql
- models/sykp/fk_sporbar_utbetaling_kafka_offsett.sql
- tests/datakvalitetsrapport/sporbar__fk_sporbar_utbetaling.sql
- tests/datakvalitetsrapport/sporbar__lest_alle_kafka_meldinger.sql
Ryddet opp i filnavn, indenteringer mv og gjort testene under:
- Testet at DBT oppretter viewet "fk_sporbar_utbetaling_kafka_offset" OK med riktig navn
- Testet at datakvalitetsrapport/sporbar__fk_sporbar_utbetaling.sql kjører OK og returnerer PASS i DBT
> Sto 3463 endre lest alle kafka meldinger-sjekken

- models/dvh_syfo/forkammer/modia/fk_modia__aktivitetskrav.sql
- models/dvh_syfo/forkammer/modia/fk_modia__dialogmote.sql
- models/dvh_syfo/forkammer/modia/fk_modia__dialogmote_patch.sql
- models/dvh_syfo/forkammer/modia/fk_modia__kandidat.sql
Ga feil antall dialogmøter trolig pga sommer-/vintertid-problematikk. Må finne annen måte å sette ny timezone på.
> Revert "endrer fra navn til time zone offset pga thin mode changes mars 2023"

- models/dvh_syfo/torg/fak_dialogmote.sql
Testet med Elisabeth og Thea.
Se sak [STO-3611](https://jira.adeo.no/browse/STO-3611)
> Sto 3611 dialogmote avholdt dato null håndtering

- models/dvh_syfo/torg/fak_dialogmote.sql
Kommenterer ut unntaksaårsak i påvente av endring. Må hente siste unntaksårsak istedenfor første på sf-tilfellet.
> Kommentere ut unntakarsak

- models/dvh_syfo/kjerne/mk_dialogmote__pivotert.sql
- models/dvh_syfo/kjerne/mk_dialogmote__union.sql
- models/dvh_syfo/torg/fak_dialogmote.sql
Se oppgavebeskrivelse her: https://jira.adeo.no/browse/STO-4151
Testet at antall dm ikke endres når ekstra kolonne kommer med.
> Sto 4151 regional oppf enhet flagg

- models/dvh_syfo/kjerne/mk_dialogmote__omkode_arena_hendelse.sql
- models/dvh_syfo/kjerne/mk_dialogmote__pivotert.sql
- models/dvh_syfo/torg/fak_dialogmote.sql
Tar bort unntaksarsaker med Arenadata. Ny PR kommer med unntaksårsaker fra kun Modia.
> Feat sto 3374  tar bort unntaksarsaker fra arena

- models/dvh_syfo/kjerne/mk_dialogmote__pivotert.sql
- models/dvh_syfo/torg/fak_dialogmote.sql
Legger til ny CTE for unntakarsak_modia. Joiner og lister felt
> initial commit: add cte unntakarsak_modia, list fields

- models/dvh_syfo/dvh_syfo_all_models.yml
- Lagt på beskrivelse av tabell fak_dialogmote
- Lagt på beskrivelse av kolonner i tabell fak_dialogmote 
Alt i fil dvh_syfo_all_models.yml.
> STO-4362 Oppdatere kommentarer på fak_dialogmote

- models/syfra/agg_ia_sykefravar/agg_ia_sykefravar__land.sql
- models/syfra/agg_ia_sykefravar/agg_ia_sykefravar__naering.sql
- models/syfra/agg_ia_sykefravar/agg_ia_sykefravar__naeringskode.sql
- models/syfra/agg_ia_sykefravar/agg_ia_sykefravar__sektor.sql
- models/syfra/agg_ia_sykefravar/agg_ia_sykefravar__virksomhet.sql
- models/syfra/agg_ia_sykefravar/agg_ia_sykefravar__virksomhet_metadata.sql
Endrer casting fordi (number,presisjon) ikke var høyt nok, samt sørger for å håndtere null-verdi i muligedv.
> Sto 3773 nye views team pia

- models/sykp/_sykp__models.yml
- models/sykp/_sykp__sources.yml
- models/sykp/staging/stg_sykp__arbeidsgiver_oppdrag.sql
- models/sykp/staging/stg_sykp__person_oppdrag.sql
- models/sykp/staging/stg_sykp__utbetaling.sql
- models/sykp/staging/stg_sykp__vedtak.sql
Pakka ut vedtak frå raw_vedtak og utbetalingar frå raw_utbetaling. Endra i yml-fil.
> STO-4081 utpakking sykp

- package-lock.yml
- packages.yml
Retta feil for å få til å køyre jobbar
> Feilretting

- models/sykp/_sykp__models.yml
- models/sykp/staging/stg_sykp__annullering.sql
- package-lock.yml
- packages.yml
Lagt til utpakking av SYKP-annulleringar.
Køyrt manuelt i prod, resultat OK.
Ser at eg ikkje kan merge automatisk, så må sikkert ha litt hjelp for å få til det.
> Sto 4081 syp annullering

- models/sykp/_sykp__models.yml
- models/sykp/_sykp__sources.yml
Har tatt bort alt som har med fk_sporbar å gjere i sykp_models.yml og sykp_sources.yml.
Dette for å unngå at det kjem varsling på slack om feil i freshness på sporbar-tabellane.
> Fjerna alt vedr fk_sporbar i sykp_models.yml og sykp_sources.yml

- models/dvh_syfo/dvh_syfo_all_models.yml
> Dokumentasjon agg_fak_dialogmote_sub

- models/dvh_syfo/forkammer/modia/fk_modia__kandidat.sql
da blir det automatisk med i mk_dialogmote__union når eg opprettar det viewet på nytt.
> Pakkar ut unntakVeilederident til fk_modia__kandidat, kallar feltet nav_ident, 

- models/sykm/forkammer/stg_fak_sykm_sykefravar_tilfelle.sql
- models/sykm/forkammer/sykm_informatica/_sykm_informatica__sources.yml
- models/sykm/forkammer/sykm_informatica/fk_dk_sensitiv__syk_sykmelding.sql
- models/sykm/forkammer/sykm_informatica/fk_dvh_sykm__fak_sykm_sykefravar_tilfelle.sql
- models/sykm/forkammer/sykm_informatica/fk_dvh_sykm__sykm_periode.sql
- models/sykm/forkammer/sykm_informatica/fk_fk_sensitiv__hist_ff_lsp_sykmelding.sql
- models/sykm/sources.yml
- models/sykm/torg/sykm_til_os.sql
- tests/datakvalitetsrapport/sykm__lest_alle_kafka_meldinger.sql
Reverts navikt/dvh-sykefravar-dmx#72
> Revert "Sto 5017 slett sykm"

- models/sykm/forkammer/sykm_informatica/_sykm_informatica__sources.yml
- models/sykm/forkammer/sykm_informatica/fk_dk_sensitiv__syk_sykmelding.sql
- models/sykm/forkammer/sykm_informatica/fk_dvh_sykm__fak_sykm_sykefravar_tilfelle.sql
- models/sykm/forkammer/sykm_informatica/fk_dvh_sykm__sykm_periode.sql
- models/sykm/forkammer/sykm_informatica/fk_fk_sensitiv__hist_ff_lsp_sykmelding.sql
- models/sykm/sources.yml
- models/sykm/torg/sykm_til_os.sql
- tests/datakvalitetsrapport/sykm__lest_alle_kafka_meldinger.sql
Reverts navikt/dvh-sykefravar-dmx#76
> Revert "STO-5017 sletta sykm-ting, men ikkje stg_fak_sykm_sykefravar_tilfelle"
